Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: (ENV["SPRING_BOARD_SERVER_ADDRESS"] || "192.168.33.100")
  config.vm.provision "shell", inline: <<~SHELL
    yum upgrade -y
    yum install -y epel-release
    yum install -y NetworkManager-l2tp
    systemctl enable firewalld
    systemctl start firewalld
    firewall-cmd --zone=external --add-masquerade --permanent
    firewall-cmd --reload
  SHELL
end
